export const MyMovies = [
  'John Wick',
  'Bad Boys for Life',
  'The Lion King',
  'Jurassic World Fallen Kingdom',
  'Bloodshot',
  'Motherless Brooklyn',
  'Transformers The Last Knight',
  'Birds of Prey',
  'Barbie and the Diamond Castle',
  'The Platform',
  'Underwater',
  'Star Wars The Rise of Skywalker',
  'Sonic the Hedgehog',
  'Hotel Transylvania',
  'Jumanji The Next Level',
  'The Invisible Man',
  'Atlantis The Lost Empire',
  'Geostorm',
  'Onward',
  'Die Hard With a Vengeance',
  'Daughter of Darkness',
  'The Hunt',
  'The Call of the Wild',
  'Parasite',
  'Cinderella Dreams Come True',
  'Joker',
  'Gladiator',
  'Knives Out',
  'The Gentlemen',
  'Asterix The Secret of the Magic Potion',
  'Dolittle',
  'Contagion',
  'Female Urologists',
  'The Goonies',
  'Cars',
  'One Flew Over the Cuckoos Nest',
  'Licence to Kill',
  'A Rainy Day in New York',
  'Miracle in Cell No 7',
  'Little Women',
  'Frozen',
  'Harry Potter and the Philosophers Stone',
  '365 Days',
  'Percy Jackson Sea of Monsters',
  'Ant Man',
  'John Wick',
  'Once Upon a Time in Hollywood',
  'Spies in Disguise',
  'Star Wars',
  'Escape from Pretoria',
  'Aladdin',
  'The Lord of the Rings The Fellowship of the Ring',
  'Avengers Infinity War',
  'Ant Man and the Wasp',
  'Maleficent Mistress of Evil',
  'Terminator Dark Fate',
  'The Decline',
  'Vivarium',
  '6 Below Miracle on the Mountain',
  'Spider Man Far from Home',
  'Ford v Ferrari',
  'Mission Impossible Fallout',
  'Midway',
  'The Way Back',
  'Spenser Confidential',
  'Ultras',
  'The Bourne Ultimatum',
  'Olympus Has Fallen',
  'The Twilight Saga Eclipse',
  'The Occupant',
  'The Lord of the Rings The Return of the King',
  'Harry Potter and the Chamber of Secrets',
  'Guns Akimbo',
  'Just Mercy',
  'Jojo Rabbit',
  'Zootopia',
  'The Shawshank Redemption',
  'Gemini Man',
  'Uncorked',
  'Captain Marvel',
  'Scooby Doo and the Monster of Mexico',
  'Avengers Endgame',
  'Rambo Last Blood',
  'Pirates of the Caribbean The Curse of the Black Pearl',
  'The Irishman',
  'It Chapter Two',
  'Red Shoes and the Seven Dwarfs',
  'Gone Girl',
  'Avengers Age of Ultron',
  'Interstellar',
  'I Still Believe',
  'Deadpool',
  'Doctor Strange',
  'Journey to China The Mystery of Iron Mask',
  'Pelican Blood',
  'The Banker',
  'Digimon Adventure Last Evolution Kizuna',
  'The Matrix',
  'Frozen',
  'Fury',
  'Star Wars The Last Jedi',
  'Maddy',
  'The Hobbit The Battle of the Five Armies',
  'Black Panther',
  'Battlestar Galactica Blood and Chrome',
  'The Coma',
  'Rogue One A Star Wars Story',
  'Blade Runner 2049',
  'Iron Man',
  'Terminator Genisys',
  'Angel Has Fallen',
  'Star Wars The Force Awakens',
  'Shazam',
  'Men in Black',
  'Blood Father',
  'Dragon Ball Z Fusion Reborn',
  'Sub Rosa',
  'Howls Moving Castle',
  'Captain America Civil War',
  'The Fifth Element',
  'Spider Man Homecoming',
  'Ready or Not',
  'Inception',
  'The Grudge',
  'Harry Potter and the Half Blood Prince',
  'Coco',
  'Harry Potter and the Order of the Phoenix',
  'Whiplash',
  'The Avengers',
  'Last Christmas',
  'Togo',
  'Harry Potter and the Deathly Hallows',
  'Spirited Away',
  'The Dark Knight',
  'Bee Movie',
  'The Godfather',
  'Hustlers',
  'Pulp Fiction',
  'Toy Story',
  'Titanic',
  'Up',
  'Doctor Sleep',
  'Marriage Story',
  'The Maze Runner',
  'Get Out',
  'The November Man',
  'The Other Lamb',
  'The Empire Strikes Back',
  'Stargirl',
  'Django Unchained',
  'Man of Steel',
  'Black Widow',
  'To All the Boys I have Loved Before',
  'El Camino',
  'The Current War',
  'A Quiet Place',
  'The Devil Wears Prada',
  'Avatar',
  'Wonder Woman',
  'The Lighthouse',
  'Bohemian Rhapsody',
  'Dark Phoenix',
  'Thor Ragnarok',
  'WALL E',
  'Justice League',
  'Green Book',
  'Schindlers List',
  'Stuber',
  'Abominable',
  'Iron Man',
  'The Hidden Face',
  'Lazy Susan',
  'Charlies Angels',
  'How to Train Your Dragon The Hidden World',
  'Smurfs The Lost Village',
  'Guardians of the Galaxy',
  'Child 44',
  'The Hunger Games Mockingjay',
  'Godzilla King of the Monsters',
  'Ready Player One',
  'Alien Covenant',
  'Lady and the Tramp',
  'Solo A Star Wars Story',
  'Fight Club',
  'Bad Boys',
  'Jurassic Galaxy',
  'The Shining',
  'The Truman Show',
  'Tomorrowland',
  'Pokemon Detective Pikachu',
  'The Uncertain Kingdom',
  'My Neighbor Totoro',
  'X Men Days of Future Past',
  'The Terminator',
  'Inglourious Basterds',
  'Harry Potter and the Prisoner of Azkaban',
  'Zombieland Double Tap',
  'Monsters Inc',
  'Aladdin',
  'Toy Story',
  'Inside Out',
  'Spider Man Into the Spider Verse',
  '300 Rise of an Empire',
  'Brave',
  'Richard Jewell',
  'Blade Runner',
  'Kill Bill',
  'Star Wars',
  'Your Name',
  'Dracula Untold',
  'Maleficent',
  'Wild Card',
  'The Perfect Date',
  'GoodFellas',
  'Harry Potter and the Deathly Hallows',
  'The Lord of the Rings The Two Towers',
  'The Princess Diaries',
  'The Invisible Guest',
  'Forrest Gump',
  'Black and Blue',
  'Bad Boys',
  'Men in Black',
  'Shrek',
  'The Great Mouse Detective',
  '30 Days of Night Dark Days',
  'The Imitation Game',
  'Desire',
  'Nater Guru',
  'The Martian',
  'Rampage',
  'World War Z',
  'Shrek',
  'American Beauty',
  'The Matrix Reloaded',
  'The Matrix Revolutions',
  'Beauty and the Beast',
  'Mad Max Fury Road',
  'Braveheart',
  'Outbreak',
  'The Mask',
  'The Hobbit An Unexpected Journey',
  'Event Horizon',
  'Men in Black International',
  'Live Free or Die Hard',
  'Trainspotting',
  'Arrival',
  'Ralph Breaks the Internet',
  'Nightcrawler',
  'Back to the Future',
  'Shutter Island',
  'Cinderella',
  'The Kissing Booth',
  'The Wolf of Wall Street',
  'Sixteen Candles',
  'Sinbad and the Eye of the Tiger',
  'Kiss and Kill',
  'The Equalizer',
  'Twilight',
  'Predator',
  'Isi and Ossi',
  'Big Hero 6',
  'Aquaman',
  'I Am Legend',
  'Teenage Mutant Ninja Turtles',
  'The Twilight Saga New Moon',
  'The Equalizer',
  'Alita Battle Angel',
  'Uncut Gems',
  'Venom',
  'Indiana Jones and the Last Crusade',
  'Raiders of the Lost Ark',
  'Toy Story',
  'Se7en',
  'Hereditary',
  'From Russia with Love',
  'The Last Summer',
  'Batman Begins',
  'Us',
  'Insurgent',
  'Logan',
  'Troy',
  'Ice Age',
  'After the Sunset',
  'I Robot',
  'Death Race Beyond Anarchy',
  'Dances with Wolves',
  'Code 8',
  'Harry Potter and the Goblet of Fire',
  'Thor',
  'After',
  'Trolls World Tour',
  'Finding Nemo',
  'Dragonheart Vengeance',
  'The Flu',
  'The Dividing Wall',
  'Batman v Superman Dawn of Justice',
  'Game of Thrones Conquest and Rebellion',
  'The Shack',
  'Oldboy',
  'Ice Age The Meltdown',
  'Jurassic World',
  'Triple Threat',
  'The Good the Bad and the Ugly',
  'Countdown',
  'Fantastic Beasts and Where to Find Them',
  'The Meg',
  'Fantasy Island',
  'The Dark Knight Rises',
  'Resistance',
  'Despicable Me',
  'Hidden Figures',
  'Terminator 2 Judgment Day',
  'Downhill',
  '28 Days Later',
  'Incredibles',
  'Jocks',
  'The Secret Life of Pets',
  'Spider Man',
  'The Green Mile',
  'Deadpool',
  'Cars',
  'Taxi Driver',
  'Ex Machina',
  'Ponyo',
  'How to Train Your Dragon',
  'Return of the Jedi',
  'The Captive',
  'Gattaca',
  'Saving Private Ryan',
  'Sorry We Missed You',
  'Once Upon a Time in America',
  'Cold Blood',
  '21 Bridges',
  'First Man',
  'The Invasion',
  'Oceans Twelve',
  'The Jungle Book',
  'Split',
  'Cats',
  'Guardians of the Galaxy',
  'Dora and the Lost City of Gold',
  'Psycho',
  'The Lion King',
  'Casino Royale',
  'A Bugs Life',
  'Cloudy with a Chance of Meatballs',
  'The Curious Case of Benjamin Button',
  'Bad Times at the El Royale',
  'Baby Driver',
  'The Smurfs',
  'Maze Runner The Death Cure',
  '2001 A Space Odyssey',
  'The Purge Anarchy',
  'Dark Waters',
  'Bombshell',
  'Iron Man',
  'Pretty Woman',
  'Spectre',
  'The Great Gatsby',
  'Alien',
  'Star Trek',
  'Peter Pan',
  'Wonder',
  'A Cinderella Story If the Shoe Fits',
  'Fighting with My Family',
  'Ratatouille',
  'The Hangover',
  'Lion',
  'Descendants',
  'Replicas',
  'Tomorrow Never Dies',
  'Den of Thieves',
  'How to Train Your Dragon',
  'Sinister Seduction',
  'A Star Is Born',
  'Dawn of the Planet of the Apes',
  'The Hunt',
  'Spider Man',
  'Haunt',
  'Midnight in Paris',
  'The Little Mermaid',
  'Mr and Mrs Smith',
  'Sniper Ultimate Kill',
  'Eyes Wide Shut',
  'Zombieland',
  'Kong Skull Island',
  'Glass',
  'Chappie',
  'Skyfall',
  'Fantastic Beasts The Crimes of Grindelwald',
  'Train to Busan',
  'Ip Man The Finale',
  'The Informer',
  'Five Feet Apart',
  'A Nightmare on Elm Street Part',
  'Beauty and the Beast',
  'The Predator',
  'Jaws',
  'Superman',
  'Master and Commander The Far Side of the World',
  'The World Is Not Enough',
  'Jupiter Ascending',
  'The Big Lebowski',
  'And What Is He Like',
  'Playing with Love',
  'Reservoir Dogs',
  'Life Is Beautiful',
  'Dracula',
  'Ghostbusters',
  'Me Before You',
  'Star Trek Into Darkness',
  'No Time to Die',
  'American Sniper',
  'Die Hard',
  'Bruce Almighty',
  'Toy Story',
  'Pet Sematary',
  'All the Bright Places',
  'Pearl Harbor',
  'Jumanji Welcome to the Jungle',
  'Monsters University',
  'Taken',
  'The Good Liar',
  'The Room',
  'Curiosa',
  'Thor The Dark World',
  'Sea Fever',
  'Beetlejuice',
  'Alvin and the Chipmunks Chipwrecked',
  'The Boy',
  'Alice in Wonderland',
  'Black Christmas',
  'Cast Away',
  'Alice in Wonderland',
  'Close Encounters of the Third Kind',
  'The Revenant',
  'The Hobbit The Desolation of Smaug',
  'La La Land',
  'Mulan',
  'The Autopsy of Jane Doe',
  'Kingsman The Golden Circle',
  'Sherlock Holmes',
  'Hellboy',
  'Jan Dara',
  'Fifty Shades of Grey',
  'Night at the Museum Secret of the Tomb',
  'Skyscraper',
  'The Incredible Hulk',
  'Collateral Beauty',
  'Portrait of a Lady on Fire',
  'The Patriot',
  'Its a Wonderful Life',
  'Exodus Gods and Kings',
  'Her',
  'Paul Blart Mall Cop',
  '10 Cloverfield Lane',
  'X Men Apocalypse',
  'Scarface',
  'Anna',
  '6 Underground',
  'Airplane',
  'How to Be Single',
  'Terminator Rise of the Machines',
  'Star Trek Beyond',
  'Superman',
  'Minority Report',
  'The Pianist',
  'Monty Python and the Holy Grail',
  'Twelve Monkeys',
  'Mission Impossible Ghost Protocol',
  'Fifty Shades Freed',
  'Princess Mononoke',
  'Star Trek V The Final Frontier',
  'Gangs of New York',
  'No Country for Old Men',
  'The Incredibles',
  'Castle in the Sky',
  'The Transporter',
  'Taken',
  'Safe House',
  'Angels and Demons',
  'Frankenstein',
  'Determined',
  'Jurassic Park',
  'Chunky Shrapnel',
  'Survivor',
  'Hacksaw Ridge',
  'The Scheme',
  'An Officer and a Spy',
  'Furious 7',
  'Pitch Perfect',
  'Kingdom of Heaven',
  'Annabelle Creation',
  'Black Swan',
  'The Interview',
  'A Walk Among the Tombstones',
  'Lady and the Tramp',
  'Quantum of Solace',
  'The Godfather',
  'Rocky',
  'American History X',
  'Pride and Prejudice',
  'Game Night',
  'Madagascar Escape to Africa',
  'GoldenEye',
  'The Fate of the Furious',
  'A Haunted House',
  'Rules of Engagement',
  'The Adventures of Tintin',
  'Lady Bird',
  'First Blood',
  'Nymphomaniac',
  'Acts of Vengeance',
  'Spotlight',
  'Chicken Run',
  'Bumblebee',
  'Queen and Slim',
  'Grease',
  'Hercules',
  'Memento',
  'Crocodile Dundee',
  'Cinderella',
  'Red Sparrow',
  'Hercules',
  'Annabelle Comes Home',
  'Tremors',
  'My Spy',
  'Dumbo',
  'The Angry Birds Movie',
  'Transformers Age of Extinction',
  'Rambo First Blood Part',
  '47 Meters Down Uncaged',
  'Ghostbusters',
  'Hotel Transylvania Summer Vacation',
  'Lucy',
  'Doom Annihilation',
  'The Amazing Spider Man',
  'The Usual Suspects',
  'X Men Production Scrapbook',
  'Casino',
  'Death Wish',
  'Eduardo and Monica',
  'The Amazing Spider Man',
  'One Hundred and One Dalmatians',
  'Scott Pilgrim vs the World',
  'The Purge',
  'Prometheus',
  'Sex Tape',
  'Armageddon',
  'Ice Princess',
  'Untitled Spider Man',
  '2012',
  'To All the Boys PS I Still Love You',
  'The Lorax',
  'Star Trek IV The Voyage Home',
  'The Bourne Identity',
  'The Concubine',
  'The Hateful Eight',
  'Batman Returns',
  'Despicable Me',
  'Kingsman The Secret Service',
  'The Mummy',
  'The Addams Family',
  'The Drop',
  'The Intouchables',
  'Barbie as The Princess and the Pauper',
  'Rise of the Planet of the Apes',
  'Call Me by Your Name',
  'The Notebook',
  'Wolf Warrior',
  'Groundhog Day',
  'Mulan',
  'Malik and Elsa',
  'Pixels',
  'Thunderball',
  'Tangled',
  'Apollo 13',
  'Now You See Me',
  'Brightburn',
  'Wreck It Ralph',
  'Heat',
  'Total Recall',
  'Constantine',
  '10 Things I Hate About You',
  'Dumb and Dumber',
  'Dragon Ball Z Broly The Legendary Super Saiyan',
  'The Hustle',
  'Alien',
  'Snowpiercer',
  'Tarzan',
  'Escape from Alcatraz',
  'Crawl',
  '12 Angry Men',
  'Annihilation',
  'The Kitchen',
  'Tracers',
  'The Expendables',
  'Mission Impossible',
  'Coraline',
  'Shrek the Third',
  'RoboCop',
  'Goldfinger',
  'The Prestige',
  'Batman Forever',
  '300',
  'Aliens',
  'Conan the Barbarian',
  'The Godfather',
  'Bikini Valley Car Wash',
  'Once Upon a Deadpool',
  'Shaun of the Dead',
  'Captain Fantastic',
  'Pacific Rim',
  'Trainwreck',
  'Apocalypse Now',
  'Lost Girls',
  'The Gods Must Be Crazy',
  'Pinocchio',
  'The Taming of the Scoundrel',
  'Shrek Forever After',
  'Hot Girls Wanted',
  'The Wolfs Call',
  'Away',
  'Million Dollar Baby',
  'Independence Day',
  'Shipwrecked',
  'The Girl Who Killed Her Parents',
  'Tomb Raider',
  'Ted',
  'Commando',
  'The Sixth Sense',
  'Escape Plan',
  'Mission Impossible Rogue Nation',
  'Superintelligence',
  'A Hidden Life',
  'The Purge Election Year',
  'Cheeky',
  'Instant Family',
  'The Spy Who Dumped Me',
  'Clash of the Titans',
  'Southpaw',
  'Crank',
  'The Parts You Lose',
  'Sing',
  'Ninja Assassin',
  'The Book of the Sea',
  'Valerian and the City of a Thousand Planets',
  'The Simpsons Movie',
  'Fantasia 2000',
  'The Departed',
  'Fantastic Four Rise of the Silver Surfer',
  'Bird Box',
  'Point Break',
  'Night at the Museum',
  'James and the Giant Peach',
  'Batman and Robin',
  'Official Secrets',
  'Catch Me If You Can',
  'Into the Woods',
  'Law Abiding Citizen',
  'Stargate',
  'Weathering with You',
  'Color Out of Space',
  'Limitless',
  'War Dogs',
  'Full Metal Jacket',
  'The Animal',
  'I Kill Giants',
  'The Hunger Games',
  'Robin Hood',
  'Divergent',
  'Poltergeist',
  'Corpse Bride',
  'The Lego Movie',
  'Rocketman',
  'Snow White and the Seven Dwarfs',
  'The Worlds End',
  'Snatch',
  'Love Story',
  'Donnie Darko',
  'Boomerang',
  'Creed',
  'Indiana Jones and the Temple of Doom',
  'The Boy Who Killed My Parents',
  'War of the Worlds',
  'The Hunger Games Catching Fire',
  'Hot Fuzz',
  'Little',
  'Pans Labyrinth',
  'American Pie',
  'Lets Be Cops',
  'Blade',
  'Gone in Sixty Seconds',
  'The Golden Compass',
  'The Twilight Saga Breaking Dawn',
  'Kung Fu Panda',
  'The Mule',
  'Secretary',
  'The Courier',
  'Dial M for Murder',
  'Dragon Ball Z Broly Second Coming',
  'V for Vendetta',
  'The Criminal Man',
  'Bad Company',
  'Sherlock Holmes A Game of Shadows',
  'Okja',
  'Batman The Dark Knight Returns',
  'Bastille Day',
  'A Fistful of Dollars',
  'Dirty Dancing',
  'Home Alone Lost in New York',
  'How to Train Your Dragon Homecoming',
  'The Host',
  'London Has Fallen',
  'The Hitmans Bodyguard',
  'Jumper',
  'The Good Dinosaur',
  'Death Proof',
  'Paradise Drifters',
  'Lethal Weapon',
  'Fearless',
  'Batman',
  'The Boy Who Harnessed the Wind',
  'Hulk',
  'It Follows',
  'Down by Law',
  'Wrong Turn Left for Dead',
  'Blackhat',
  'A View to a Kill',
  'Passengers',
  'Watchmen',
  'Wild Child',
  'Cars',
  'The Lone Ranger',
  'Rocky',
  'Chaos',
  'Norbit',
  'Final Fantasy VII Advent Children',
  'King Kong',
  'Megamind',
  'Primal',
  'A Fall From Grace',
  'After Porn Ends',
  'The Magnificent Seven',
  'Mirror Mirror',
  'BlacKkKlansman',
  'Gran Torino',
  'Private Lessons',
  'Barbie Mariposa',
  'The Pursuit of Happiness',
  'Wind River',
  'The Shape of Water',
  'The Ant Bully',
  'Zodiac',
  'Saw',
  'Dallas Buyers Club',
  'Unfaithful',
  'Must Be Love',
  'Once Upon a Time in the West',
  'Spawn',
  'High Strung',
  'Anchorman The Legend of Ron Burgundy',
  'Annabelle',
  'The Librarian Quest for the Spear',
  'Unbreakable',
  'National Treasure',
  'All the Presidents Men',
  'Mirage',
  'Die Hard',
  'The Snowman',
  'A Nightmare on Elm Street',
  'Eternal Sunshine of the Spotless Mind',
  'Sin City',
  'Mission Impossible',
  'Nocturnal Animals',
  'Oldboy',
  'The First Purge',
  'Army of Darkness',
  'Fantastic Four',
  'The Expendables',
  'Sully',
  'Men in Black',
  '12 Years a Slave',
  'Murder Mystery',
  'Music and Lyrics',
  'I Am Number Four',
  'Ice Age Dawn of the Dinosaurs',
  'ET the Extra Terrestrial',
  'The Eagle Huntress',
  'Jigsaw',
  'Slumdog Millionaire',
  'Only the Brave',
  'Enemy at the Gates',
  'Goosebumps',
  'A Prayer Before Dawn',
  'Clueless',
  'Shot Caller',
  'Kajillionaire',
  'Hop',
  'The Florida Project',
  'War for the Planet of the Apes',
  'Paradise Hills',
  'Captain America The Winter Soldier',
  'Atomic Blonde',
  'Sicario',
  'Mission to Mars',
  'Minions',
  'The Karate Kid',
  'Akira',
  'The Greatest Showman',
  'The Gods Must Be Crazy',
  'You have Got Mail',
  'The Croods',
  'The Kangaroo Chronicles',
  'Halloween',
  'Alien Resurrection',
  'The Favourite',
  'Logan Lucky',
  'Into the Wild',
  'Oceans Eleven',
  'Tarzan',
  'Kung Fu Panda',
  'Finding Dory',
  'Transporter',
  'Mortal Engines',
  'Perfume The Story of a Murderer',
  'Good Will Hunting',
  'Penguins of Madagascar',
  'Shark Tale',
  'A Good Day to Die Hard',
  'Upgrade',
  'Grimsby',
  'The Traitor',
  'Are We There Yet',
  'Pride and Glory',
  'No Way Out',
  'Belle',
  'Scary Stories to Tell in the Dark',
  'The Rescuers',
  'Guess Who',
  'The Elephant Man',
  'Allegiant',
  'Life',
  'Maze Runner The Scorch Trials',
  'Swallow',
  'The Great Wall',
  'Death Race',
  'Mulan',
  'Murder on the Orient Express',
  'Charlies Angels',
  'Bambi',
  'Lethal Weapon',
  'The Butterfly Effect',
  'The Girl Next Door',
  'Oceans Eight',
  'Jay and Silent Bob Reboot',
  'Come to Daddy',
  'Bambi',
  'The Dating List',
  'The SpongeBob Movie Sponge Out of Water',
  'The Deer Hunter',
  'Cowboys and Aliens',
  'Sucker Punch',
  'Miracles from Heaven',
  'The Jungle Book',
  'Hitch',
  'Charlie and the Chocolate Factory',
  'The Guns of Navarone',
  'Mary Poppins Returns',
  'Waynes World',
  'The Intern',
  'The Chronicles of Narnia The Voyage of the Dawn Treader',
  'The Final Destination',
  'Open Season',
  'Mandy',
  'The Next Three Days',
  'Suicide Squad',
  'The Great Debaters',
  'King Arthur Legend of the Sword',
  'Total Recall',
  'Gravity',
  'mother',
  'Jack Reacher',
  'Drive',
  'The Loft',
  'Horse Girl',
  'The Peanut Butter Falcon',
  'Citizen Kane',
  'Sexual Chronicles of a French Family',
  'Warcraft',
  'Beowulf',
  'Seventh Son',
  'Beauty and the Beast The Enchanted Christmas',
  'The 5th Wave',
  'The Man Who Knew Too Much',
  'The Polar Express',
  'The Commuter',
  'Homefront',
  'Terminator Salvation',
  'Begin Again',
  'The Angry Birds Movie',
  'The Last House on the Left',
  'Legends of the Fall',
  'The Animatrix',
  'Wallace and Gromit The Curse of the Were Rabbit',
  'Mortal Kombat Legends Scorpions Revenge',
  'A Cinderella Story Christmas Wish',
  'Below Her Mouth',
  'Blow',
  'Eye for an Eye',
  'Modern Times',
  'Yesterday',
  'The Wizard of Oz',
  'Texas Chainsaw',
  'Homeward Bound The Incredible Journey',
  'A Beautiful Mind',
  'American Psycho',
  'Serenity',
  'The Vanishing',
  'Pacific Rim Uprising',
  'The 6th Day',
  'The Accountant',
  'American Wedding',
  'Second Act',
  'Vertigo',
  'Furry Vengeance',
  'Dinosaur',
  'A Real Young Girl',
  'Inherent Vice',
  'The Wedding Ringer',
  'Oblivion',
  'Robots',
  'Time Out of Mind',
  'The Wind Rises',
  'Seven Pounds',
  'The Spy Who Loved Me',
  'Come and See',
  'Run All Night',
  'Edward Scissorhands',
  '8 Mile',
  'The Wandering Earth',
  'Cold Pursuit',
  'Sierra Burgess Is a Loser',
  'Before I Go to Sleep',
  'Mollys Game',
  'Kick Ass',
  'The Boy in the Striped Pyjamas',
  'Transporter',
  'The Cat Returns',
  'Unhinged',
  'The Dark Tower',
  '9 Songs',
  'Barnyard',
  'Alice Through the Looking Glass',
  'Public Enemies',
  'Black Hawk Down',
  'Who Framed Roger Rabbit',
  'Traitor',
  'Cursed',
  'Danger Close',
  'Now You See Me',
  'The Untouchables',
  'Adrift',
  'The Prince',
  'The Girl with the Dragon Tattoo',
  'The Carnivores',
  'Madagascar',
  'Summertime',
  'Freaks',
  'Flubber',
  'The Square',
  'Hooking Up',
  'Power Rangers',
  'Platoon',
  'A Tale of Two Sisters',
  'Almost Famous',
  'The Judge',
  'Prisoners',
  'Big Mommas House',
  'Rage',
  'The Fox and the Hound',
  'Getaway',
  'Rango',
  'The Cobbler',
  'My Hero Academia Heroes Rising',
  'The Italian Job',
  'Felon',
  'Timmy Failure Mistakes Were Made',
  'Room',
  'American Factory',
  'Man on Fire',
  'San Andreas',
  'Trolls',
  'Allied',
  'Dredd',
  'Fargo',
  'Forever Young',
  'Flushed Away',
  'The Expendables',
  'An Extremely Goofy Movie',
  'The Bodyguard',
  'Boiler Room',
  'Salt',
  'Dumbo',
  'The Grand Budapest Hotel',
  'Halloween',
  'The Last Samurai',
  'Blue Lagoon The Awakening',
  'RED',
  'The Exorcism of Emily Rose',
  'The Road to El Dorado',
  'The Legend of Zorro',
  'Saw V',
  'Fantastic Four',
  'A Christmas Carol',
  'Bullet to the Head',
  'The Day the Earth Stood Still',
  'Hard Target',
  'The Man Who Knew Infinity',
  'Orphan',
  'Chicken Little',
  'The Chronicles of Narnia Prince Caspian',
  'Bridge of Spies',
  'The Intruder',
  'The Fault in Our Stars',
  'Secret Society of Second Born Royals',
  'Dead Poets Society',
  'Remember',
  'Long Shot',
  'My Moms New Boyfriend',
  'Gifted',
  'Primal Fear',
  'The King',
  'Shithouse',
  'Insidious Chapter',
  'Scary Movie',
  'Get the Gringo',
  'Life of Pi',
  'Dont Let Them In',
  'Kangaroo Jack',
  'What Lies Beneath',
  'Romeo and Juliet',
  'Chinatown',
  'Fear and Loathing in Las Vegas',
  'Kung Fu Panda',
  'Mulholland Drive',
  'Bright',
  'The Conjuring',
  'Oceans Thirteen',
  'National Treasure Book of Secrets',
  'Vice',
  'Candyman',
  'The Sword in the Stone',
  'Edge of Tomorrow',
  'Unfinished Business',
  'Isle of Dogs',
  'Who Am I',
  'Star Trek The Motion Picture',
  'Death on the Nile',
  'Sausage Party',
  'Little Monsters',
  'Cop Land',
  'Lionheart',
  '10 Days Without Mum',
  'Captain Underpants The First Epic Movie',
  'The Tourist',
  'The Lizzie McGuire Movie',
  'No Good Deed',
  'Oliver and Company',
  'Lilo and Stitch',
  'American Pie Presents The Naked Mile',
  'The Man from UNCLE',
  'Mission Impossible',
  'Ice Age Collision Course',
  'Pretty Baby',
  'Pain and Glory',
  'Creed',
  'The Prince of Egypt',
  'Kubo and the Two Strings',
  'Superman Red Son',
  'Pocahontas',
  'A Beautiful Day in the Neighborhood',
  'Atlantis Milos Return',
  'The Big Short',
  'Unforgiven',
  'She is the Man',
  'Lemony Snickets A Series of Unfortunate Events',
  'Sicario Day of the Soldado',
  'The Flyboys',
  'Source Code',
  'End of Days',
  'Eternity',
  'Dragonheart Battle for the Heartfire',
  'The Man with the Iron Fists',
  'Super Mario Bros',
  'A Little Chaos',
  'Casablanca',
  'The Addams Family',
  'Interview with the Vampire',
  'The Impossible',
  'Addams Family Values',
  'Cloverfield',
  'Rio',
  'What We Do in the Shadows',
  'You Only Live Twice',
  'Fatherhood',
  'Remember the Titans',
  'Coming to America',
  'Madagascar Europes Most Wanted',
  'Jack Reacher Never Go Back',
  'Polar',
  'At Eternitys Gate',
  'Mean Girls',
  'Disobedience',
  'Tron',
  'Moonlight',
  'Asterix and Cleopatra',
  'Kellys Heroes',
  'Insidious',
  'Con Air',
  'The Bourne Supremacy',
  'The Theory of Everything',
  'Fantastic Mr Fox',
  'Kill Bill The Whole Bloody Affair',
  'Scary Movie',
  'TRON Legacy',
  'Leaving Las Vegas',
  'Little Children',
  'The Idiots',
  'Beauty Salon Special Services',
  'The Tale of Despereaux',
  'Hitman',
  'The Adventures of Sharkboy and Lavagirl',
  'Teen Titans Go To the Movies',
  'The Aristocats',
  'Prince of Persia The Sands of Time',
  'Planet of the Apes',
  'Treasure Planet',
  'Night Shift',
  'The Mechanic',
  'Brother Bear',
  'Equilibrium',
  'City of God',
  'Resident Evil Vendetta',
  'Real Steel',
  'Lupin the Third vs Detective Conan The Movie',
  'Gone with the Wind',
  'Police Academy',
  'Descendants',
  '18 Year Old Virgin',
  'Mystic River',
  'A Simple Favor',
  'Hairspray',
  'Season of Love',
  'The Hunchback of Notre Dame',
  'Galaxy Quest',
  'The Breakfast Club',
  'Shooter',
  'In Time',
  'Sex and the City',
  'Green Lantern',
  'Possession',
  'I Still See You',
  'The Exorcist',
  'Die Another Day',
  'The Cloverfield Paradox',
  'Basic Instinct',
  'The Great Hack',
  'Cowboy Bebop The Movie',
  'Hatchet',
  'The Thing',
  'Descendants',
  'The Skeleton Key',
  'The Homesman',
  'The Mortal Instruments City of Bones',
  'Forbidden Planet',
  'Jennifers Body',
  'Mamma Mia Here We Go Again',
  'How to Be Really Bad',
  '12 Strong',
  'Pom Poko',
  'Central Intelligence',
  'The Voyeur',
  'The Sum of All Fears',
  'Charlottes Web',
  'Grace of Monaco',
  'We are the Millers',
  'Straight Outta Compton',
  'Magnum Force',
  'Sleeping Beauty',
  'Witness',
  'Along Came a Spider',
  'The Human Centipede',
  'Night Hunter',
  'Deep Impact',
  'Dirty Harry',
  'Darkest Hour',
  'Left Behind',
  'American Pie',
  'It',
  'When Marnie Was There',
  'Bicentennial Man',
  'A Night at the Roxbury',
  'Liar Liar',
  'Knowing',
  'Miss Americana',
  'Thelma and Louise',
  'Aliens vs Predator Requiem',
  'Mortdecai',
  'Austin Powers International Man of Mystery',
  'Meet Joe Black',
  'Mary Poppins',
  'Epic',
  'Sex Weather',
  'The Handmaiden',
  'Outcast',
  'Ice Age Continental Drift',
  'Predators',
  'Annie',
  'Dragon Ball Z Battle of Gods',
  'The Marine',
  'Highlander',
  'Jules and Jim',
  'The Man with the Golden Gun',
  'Planet of the Apes',
  'The Descent',
  'Dirty Dancing Havana Nights',
  'I Can Only Imagine',
  'Careful What You Wish For',
  'Diamonds Are Forever',
  'Red Joan',
  'Blood Diamond',
  'My Little Pony The Movie',
  'Forever My Girl',
  'For Your Eyes Only',
  'Pokemon Mewtwo Strikes Back Evolution',
  'The Lego Batman Movie',
  'What Women Want',
  'Enemy of the State',
  'Dunkirk',
  'Senna',
  'Moon',
  'Arlington Road',
  'Christmas with the Kranks',
  'Indiana Jones and the Kingdom of the Crystal Skull',
  'Moonrise Kingdom',
  'Hereafter',
  'Lost in Translation',
  'You Dont Mess with the Zohan',
  'Godzilla',
  'Baywatch',
  'Anastasia',
  'Lucky Number Slevin',
  'Love and Other Drugs',
  'Catwoman',
  'Mother Theory',
  'Spy Kids',
  'Alexander',
  'The Da Vinci Code',
  'Isnt It Romantic',
  '12 Hour Shift',
  'Childs Play',
  'Stolen',
  'Invasion of the Body Snatchers',
  'Striptease',
  'American Made',
  'Trauma Center',
  'Miss Peregrines Home for Peculiar Children',
  'Black Mass',
  'The Last Legion',
  'Mile 22',
  'A Shaun the Sheep Movie Farmageddon',
  'Ace Ventura Pet Detective',
  'Aladdin and the King of Thieves',
  'Rambo',
  'The Nun',
  'Forces of Nature',
  'Kiss of the Dragon',
  'The Con Is On',
  'Billy Elliot',
  'Race to Witch Mountain',
  'Ghost',
  'Predator',
  'A Clockwork Orange',
  'The Postcard Killings',
  'About Time',
  'Super',
  'Where Eagles Dare',
  'Battleship',
  'The Ballad of Buster Scruggs',
  'Overlord',
  'The High Note',
  'The NeverEnding Story',
  'The Mummy Tomb of the Dragon Emperor',
  'Hollow Point',
  'Tank Girl',
  'Juno',
  'Trinity Is Still My Name',
  'Hero',
  'Bandits',
  'Johnny English Strikes Again',
  'The Secret Life of Walter Mitty',
  'Mimic',
  'Dark Places',
  'A Good Year',
  'Pitch Perfect',
  'Moonraker',
  'I Am Mother',
  'Memories of Murder',
  'Blade',
  'The Hitchhikers Guide to the Galaxy',
  'Willy Wonka and the Chocolate Factory',
  'Amadeus',
  'Dantes Peak',
  'Thoroughbreds',
  'Chungking Express',
  'Jason Bourne',
  'Tinker Bell and the Legend of the NeverBeast',
  'Conan the Barbarian',
  'Horrible Bosses',
  'New York Minute',
  'Priest',
  'The Golden Voyage of Sinbad',
  'In the Heart of the Sea',
  'Hancock',
  'Triple Frontier',
  'Never Say Never Again',
  'Ghost in the Shell',
  'Next',
  'The Adventures of Bullwhip Griffin',
  'Miracle in Cell No 7',
  '3 Days to Kill',
  'Blazing Saddles',
  'The Whole Nine Yards',
  'Home on the Range',
  'The Devils Advocate',
  'Anita',
  'Closer',
  'Legend',
  'Beverly Hills Cop',
  'The Lion King Simbas Pride',
  'Fractured',
  'Snowden',
  'Tale of Tales',
  '28 Weeks Later',
  'The Sound of Music',
  'Collateral',
  'The Descent',
  'Silver Linings Playbook',
  '101 Dalmatians',
  'Killer Elite',
  'Riddick',
  'Cocoon',
  'High Tension',
  'Disconnect',
  'The Witch',
  'The Legend of Tarzan',
  'Hachi A Dogs Tale',
  'The Cabin in the Woods',
  'Patch Adams',
  'The Wild Bunch',
  'American Pie Presents Band Camp',
  'The Emoji Movie',
  'American Hustle',
  'The Aviator',
  'The Crow',
  'Burning',
  'Lone Survivor',
  'Olafs Frozen Adventure',
  'Natural Born Killers',
  'Inside Llewyn Davis',
  'King Arthur',
  'Bean',
  'Battle Royale',
  'Real Genius',
  'Teen Beach',
  'A Most Violent Year',
  'Miami Vice',
  'Downfall',
  'Klaus',
  'Survival Island',
  'Vera',
  'Lethal Weapon',
  'For a Few Dollars More',
  'The Help',
  'The Seventh Seal',
  'Enough Said',
  'Fifty Shades Darker',
  'The Hunchback of Notre Dame',
  'Paprika',
  'He is Just Not That Into You',
  'Daredevil',
  'Unleashed',
  'Harriet',
  'The Professor and the Madman',
  'Coyote Ugly',
  'True Romance',
  'Sinbad Legend of the Seven Seas',
  'The Lion King',
  'One Day',
  'Cake',
  'The Fog',
  'Honeydew',
  'Sex Drive',
  'Up in Smoke',
  'Hellboy',
  'Emmanuelle',
  'The Social Network',
  'Scary Movie',
  'The Island',
  'Ida',
  'John Wick',
  'What Happened to Monday',
  'Cloudy with a Chance of Meatballs',
  'Giant Little Ones',
  'The ComDads',
  'Palm Trees in the Snow',
  'The Karate Kid',
  'The Core',
  'Arthur and the Revenge of Maltazard',
  'The Wailing',
  'Hostel',
  'Tombstone',
  'Pompeii',
  'Mad Max',
  'Apocalypto',
  'The Battle of Algiers',
  'Labyrinth',
  'Chocolat',
  'Scooby Doo Monsters Unleashed',
  'RoboCop',
  'Poissonsexe',
  'The Nightmare Before Christmas',
  'The Peacemaker',
  'Outlander',
  'Whats Eating Gilbert Grape',
  '50 First Dates',
  'Speed',
  'The League of Extraordinary Gentlemen',
  'Captain Phillips',
  'Case 39',
  'Love and Death',
  'LEGO Jurassic World The Indominus Escape',
  'Parker',
  'Fist of Fury',
  'The Hedgehog',
  'Resident Evil',
  'The Hurt Locker',
  'The Giver',
  'Boomerang',
  'Blade Trinity',
  'The Mad Adventures of Rabbi Jacob',
  'Hotel Transylvania',
  'Apollo 18',
  'Superman Returns',
  'Kiss Kiss Bang Bang',
  'Insidious The Last Key',
  'Enders Game',
  '2 Guns',
  'The Fittest',
  'Surfs Up',
  'Stealth',
  'The Living Daylights',
  'Police Story',
  'Eden Lake',
  'Final Destination',
  'Early Man',
  'Scream',
  'Black Snake Moan',
  'Hellboy The Golden Army',
  'Monsters vs Aliens',
  'Changeling',
  'Jessabelle',
  'Puss in Boots',
  'I Lost',
  'Return to Never Land',
  'Serenity',
  'Son of God',
  'Seven Samurai',
  'Rob Roy',
  'Rush Hour',
  'AVP Alien vs Predator',
  'How the West Was Won',
  'Meet the Fockers',
  'Captain America The First Avenger',
  'Starship Troopers Invasion',
  'Life of Crime',
  'Mamma Mia',
  'EuroTrip',
  'Sparrows',
  'An Unfinished Life',
  'Looper',
  'Cheaper by the Dozen',
  'Hard Rain',
  'Ghost in the Shell',
  'Saw',
  'The Art of Self Defense',
  'Escape from New York',
  'Vampire Academy',
  '8MM',
  'Out of Africa',
  'Mr Holmes',
  'Safe',
  'Saw IV',
  'Must Love Dogs',
  'Newness',
  'The Texas Chainsaw Massacre The Beginning',
  'Phantom Thread',
  'Last Action Hero',
  '21 Jump Street',
  'Scream',
  'Buffalo Soldiers',
  'Suicide Kings',
  'The Mountain Between Us',
  'The Jackal',
  'Robin Hood',
  'The Package',
  'The Illusionist',
  'Miss Congeniality',
  'Every Day',
  'Young Guns',
  'Insomnia',
  'The Bourne Legacy',
  'No Strings Attached',
  'All the Money in the World',
  'Monster in Law',
  'Heavenly Creatures',
  'Accident Man',
  'Goosebumps Haunted Halloween',
  'The Royal Tenenbaums',
  'Cop Out',
  'Otherhood',
  'Spellbound',
  'Friends with Benefits',
  'The Art of War',
  'Wonder Woman 1984',
  'Alvin and the Chipmunks The Road Chip',
  'Sand Castle',
  'From Dusk Till Dawn',
  'The Blind Side',
  'Starsky and Hutch',
  'The Dirty Dozen',
  'Black Rain',
  'Money Talks',
  'Cats and Dogs',
  'How the Grinch Stole Christmas',
  'If I Stay',
  'The Blues Brothers',
  'Focus',
  'S Darko',
  'The Age of Adaline',
  'The Iron Giant',
  'The Game Plan',
  'Tinker Bell and the Pirate Fairy',
  'In the Line of Fire',
  'Mad Max Beyond Thunderdome',
  'Tell It to the Bees',
  'Rocky',
  'St Vincent',
  'Jackie Brown',
  'The Lego Movie',
  'Lara Croft Tomb Raider',
  'The Turning',
  'Contact',
  'Beverly Hills Cop ',
  'Hackers',
  'Falling Inn Love',
  'Killers',
  'Anna Karenina',
  'The Punisher',
  'Butch Cassidy and the Sundance Kid',
  'Mr Peabody and Sherman',
  'Dark Shadows',
  'Law of Desire',
  'Disturbia',
  'On the Basis of Sex',
  'WarGames',
  'I Tonya',
  'Hedwig and the Angry Inch',
  'RoboCop',
  'Marvel One Shot The Consultant',
  'Playing with Fire',
  'Rendition',
  'Gun shy',
  'Hot Bot',
  'The Scorpion King Rise of a Warrior',
  'Spy',
  'Frequency',
  'Austin Powers in Goldmember',
  'Sing Street',
  'Warrior',
  'Rocco',
  'Concussion',
  'The Tale of the Princess Kaguya',
  'The Forbidden Kingdom',
  'Step Up',
  'Amityville The Awakening',
  'Maggie',
  'Rambo',
  'Demolition Man',
  'Poseidon',
  'My Own Private Idaho',
  'Memoirs of a Geisha',
  'Dave',
  'High School Musical',
  'Elizabeth The Golden Age',
  'Eagle Eye',
  'Letters from Iwo Jima',
  'Puss in Boots The Three Diablos',
  'Block Z',
  'Delusions of Grandeur',
  'The Bridge on the River Kwai',
  'Wrong Turn',
  'Bride of Chucky',
  'Cellular',
  'The Key',
  'Free Fall',
  'Soldier',
  'Casper',
  'Kick Ass',
  'Chronicle',
  'Doctor Dolittle',
  'Godzilla',
  'District 9',
  'Eli',
  'Meet the Robinsons',
  'Insidious Chapter',
  'The Immortal',
  'Can You Hear Us Now',
  'Slaughterhouse Rulez',
  'A Serbian Film',
  'The Lobster',
  'All Things Fair',
  'The Jungle Book',
  'The English Patient',
  'What Men Want',
  'Shoplifters',
  'Kin',
  'Byzantium',
  'Rush',
  'Tropic Thunder',
  'John Carter',
  'The Proposal',
  'The Good Shepherd',
  'National Lampoons Vacation',
  'The Wing or the Thigh',
  'The Man in the Iron Mask',
  'Wild',
  'Enter the Dragon',
  'The Lost City of Z',
  'The Hunt for Red October',
  'Not Another Teen Movie',
  'Scream',
  'Three Steps Above Heaven',
  'The Grinch',
  'Night at the Museum Battle of the Smithsonian',
  'Click',
  'The Passion of the Christ',
  'The Upside',
  'Non Stop',
  'Before Sunrise',
  'Behind the Candelabra',
  'Magic Mike XXL',
  'Star Wars The Clone Wars',
  'Elle',
  'Big Trouble in Little China',
  'The Truth',
  'The Layover',
  'Happy Feet',
  'Das Boot',
  'A Perfect Murder',
  'Pretty Little Stalker',
  'The Man with the Iron Heart',
  'In the Mood for Love',
  'Let Me In',
  'Dumb and Dumber To',
  'Journey to the Center of the Earth',
  'Ghost Rider',
  'The Last Boy Scout',
  'Quarantine',
  'Good Boys',
  'Wizards of Waverly Place',
  'Crank High Voltage',
  'Johnny English',
  'TMNT',
  'The Pacifier',
  'Stonehearst Asylum',
  'Booksmart',
  'Enchanted',
  'Hard to Kill',
  'Big',
  'Raging Bull',
  'Extinction',
  'A Knights Tale',
  'The Aeronauts',
  'The Hunger Games',
  'White House Down',
  'Top Gun Maverick',
  'Scooby Doo and the Curse of the 13th Ghost',
  'A Nightmare on Elm Street',
  'Horton Hears a Who',
  'Yes Man',
  'Bridge to Terabithia',
  'Penelope',
  'Munich',
  'The Kid Who Would Be King',
  'Fatal Attraction',
  'Rush Hour',
  'Inferno',
  'Hunter Killer',
  '27 Dresses',
  'Summerland',
  'Queen of Hearts',
  'The Thin Red Line',
  'Jan Dara The Beginning',
  'The Hate U Give',
  'Time Bandits',
  'The Final Cut',
  'The Parent Trap',
  'Octopussy',
  'Starship Troopers',
  'Tales from Earthsea',
  'The Accidental Husband',
  'Robin Hood',
  'Rat Race',
  'The Wedding Date',
  'The Time Machine',
  'School of Rock',
  'The Red Pill',
  'Dennis the Menace',
  'Brother Bear',
  'Wild Things',
  'Lethal Weapon',
  'Signs',
  'Welcome to Marwen',
  'The Quick and the Dead',
  'Cool Runnings',
  'Empire of the Sun',
  'Eastern Promises',
  'Teenage Mutant Ninja Turtles Out of the Shadows',
  'Red Heat',
  'The Hangover',
  'Shaft',
  'Batman Mystery of the Batwoman',
  'Duplicity',
  'Fantasia',
  'Mowgli Legend of the Jungle',
  'The Crucifixion',
  'The Outlaw Josey Wales',
  'Day and Night',
  'Underworld',
  'Romance',
  'Universal Soldier',
  '3 Men and a Little Lady',
  'Two Weeks Notice',
  'Taxi',
  'Seeking Justice',
  'Barry Lyndon',
  'The Happening',
  'A Dogs Purpose',
  'Mirrors',
  'Blow Out',
  'The Post',
  'The Vow',
  'The Quiet',
  'Spy Kids All the Time in the World',
  'True Lies',
  'Rear Window',
  'Sublet',
  'Predestination',
  'The Girl with the Dragon Tattoo',
  'Jack Ryan Shadow Recruit',
  'A Walk to Remember',
  'Step Up 2 The Streets',
  'In Her Shoes',
  'Wrong Turn 2 Dead End',
  'This Is the End',
  'Wild Orchid',
  '24 Hours to Live',
  'Dirty Dancing',
  'Paycheck',
  'Gremlins',
  'Judy',
  'The Place Beyond the Pines',
  'Looking for Richard',
  'The Invisible Man',
  'Joy',
  'The Invisible Boy',
  'The Princess and the Frog',
  'Carbone',
  'Wedding Crashers',
  'The Saint',
  'Free Solo',
  'The Longest Day',
  'Blue Ruin',
  'Spy Intervention',
  'Ghosts of Mars',
  'Hook',
  'Manchester by the Sea',
  'The Little Mermaid',
  'Dogtooth',
  'Christopher Robin',
  'Love Actually',
  'The Counselor',
  'I Want You',
  'Normal',
  'Mr Nobody',
  'High School Musical Senior Year',
  'The Dead Pool',
  'White Chicks',
  'Dead Ringers',
  'The Human Centipede',
  'Flatliners',
  'Sleepers',
  'Into the Blue',
  'Easy A',
  'The Adjustment Bureau',
  'Fish Tank',
  'Top Gun',
  'Walk the Line',
  'Climax',
  'Sherlock Gnomes',
  'The Purity of Vengeance',
  'Green Street Hooligans',
  'Invictus',
  'Dirty Rotten Scoundrels',
  'Speed 2 Cruise Control',
  'Pet Sematary',
  'The Girl on the Train',
  'The Rock',
  'Deadgirl',
  'Tarzan and Jane',
  'Turner and Hooch',
  'Dirty Grandpa',
  'Scooby Doo',
  'American Gangster',
  'Hummingbird',
  'Undisputed',
  'Brokeback Mountain',
  'Babel',
  'Snow White and the Huntsman',
  'The 13th Warrior',
  'Ocean Waves',
  'Soul Plane',
  'Camp Rock',
  'Barely Lethal',
  'Tears of the Sun',
  'Mac and Devin Go to High School',
  'National Lampoons European Vacation',
  'Bully',
  'The Mummy',
  'The Fighter',
  'Battle Los Angeles',
  'How to Lose a Guy in 10 Days',
  'Under the Skin',
  'Nosferatu',
  'Alvin and the Chipmunks',
  'Being John Malkovich',
  'Small Soldiers',
  'The Accused',
  'Inside Man',
  'The Lovely Bones',
  'Bringing Out the Dead',
  'For Love or Money',
  'The One',
  'The Messenger',
  'Everest',
  'Barbie in The 12 Dancing Princesses',
  '101 Dalmatians',
  'Secret of the Wings',
  'Escape Room',
  'Starstruck',
  'Back to the Future Part',
  'Paddington',
  'Spirit Stallion of the Cimarron',
  'First Reformed',
  'American Pastoral',
  'The Longest Yard',
  'High Fidelity',
  'The Professor',
  'DragonHeart A New Beginning',
  'Hitman Agent 47',
  'Phone Booth',
  'Elysium',
  'Whisper of the Heart',
  'True Grit',
  'Down a Dark Hall',
  'Lincoln',
  'Nine Dead',
  'Deep Blue Sea',
  'The Silence',
  'The Black Cauldron',
  'The Saint',
  'The Last Stand',
  'Eliminators',
  'Robin Hood Prince of Thieves',
  'Tinker Bell and the Lost Treasure',
  'Dune',
  'Never Grow Old',
  'Back to the Future Part',
  'The Smurfs',
  'The Lucky One',
  'Regression',
  'Ninja Scroll',
  'Flags of Our Fathers',
  'Step Up All In',
  'Mary Queen of Scots',
  'Thirst',
  'Hugo',
  'White Men Cant Jump',
  'Operation Red Sea',
  'Ouija',
  'The Big Boss',
  'The Hole in the Ground',
  'White Fang',
  'Childs Play',
  'Notting Hill',
  'Foxcatcher',
  'Gangster Squad',
  'Here Comes the Boom',
  'Carol',
  'Bloodsport',
  'The Grudge',
  'Death Race Inferno',
  'The Other Man',
  'The Bank Job',
  'Just Like Heaven',
  'The Day the Earth Stood Still',
  'Footloose',
  'I Am Sam',
  'Saw VI',
  'Original Sin',
  'Ferris Buellers Day Off',
  'Scream',
  'Snatched',
  'The Bounty Hunter',
  'The Village',
  'Garfield A Tail of Two Kitties',
  'Eighth Grade',
  'How It Ends',
  'Ghostbusters',
  'In the House',
  'Entourage',
  'The Prince and Me',
  'Police Story Super Cop',
  'Orgazmo',
  'The Sisters Brothers',
  'Children of Men',
  'Mad Max',
  'Superbad',
  'We Own the Night',
  'Eggnoid',
  'Tinker Bell',
  'The Way of the Dragon',
  'Crazy Rich Asians',
  'The Ugly Truth',
  'Wild at Heart',
  'Underworld Rise of the Lycans',
  'Closed Circuit',
  'Cocktail',
  'The Mummy Returns',
  'Conan the Destroyer',
  'Once Upon a Time in Mexico',
  'That Awkward Moment',
  'Lord of War',
  'The Apartment',
  'The Great Escape',
  'Ted',
  'Nerve',
  'Sabotage',
  'The Ring',
  'Good Time',
  'Playing It Cool',
  'The Haunting',
  'Ballerina',
  'Raw',
  'Sabrina',
  'High Plains Drifter',
  'The Host',
  'Cold Mountain',
  'Last Tango in Paris',
  'Money Monster',
  '48 Hrs',
  'The Dirt',
  'Cinderella Man',
  'Employee of the Month',
  'Wild Wild West',
  'Grown Ups',
  'Argo',
  'Shrink',
  'Escape Room',
  'Mr Poppers Penguins',
  'The Fugitive',
  'The Darjeeling Limited',
  'I Dont Know How She Does It',
  'Star Trek First Contact',
  'Peppermint',
  'A Fish Called Wanda',
  'Teen Titans The Judas Contract',
  'Hobo with a Shotgun',
  'The Other Boleyn Girl',
  'Valkyrie',
  'The Terminal',
  'Blow the Man Down',
  'Seed of Chucky',
  'Escape Plan',
  'Before I Fall',
  '22 Jump Street',
  'Bolt',
  'Live by Night',
  'Absolute Power',
  'Any Given Sunday',
  'Ice Age A Mammoth Christmas',
  'Bullitt',
  'The Dreamers',
  'Mona Lisa Smile',
  'Rush Hour',
  'The Day After Tomorrow',
  'Jackass The Movie',
  'The Women',
  'Foxtrot Six',
  'The Eagle Has Landed',
  'Planet Terror',
  'Despicable Me',
  'Altitude',
  'Fun with Dick and Jane',
  'Shanghai Knights',
  'Crazy Stupid Love',
  'Crash',
  'Patton',
  'The Fly',
  'Spies Like Us',
  'Panic Room',
  'Sextuplets',
  'The Death of Superman',
  'The Leopard',
  'RED',
  'The Legend of Bagger Vance',
  'To Rome with Love',
  'The Lover',
  'Willow',
  'Pet Sematary',
  'Boruto Naruto the Movie',
  'The Oranges',
  'It Takes Two',
  'The House Bunny',
  'First They Killed My Father',
  'Bitter Moon',
  'The Young Victoria',
  'Oz the Great and Powerful',
  'Irreversible',
  'Defiance',
  'Beautiful Creatures',
  'Unstoppable',
  'Jaws The Revenge',
  'Kursk',
  'The Sorcerers Apprentice',
  'Punisher War Zone',
  'Deepwater Horizon',
  'The Hills Have Eyes',
  'Michael',
  'Matilda',
  'There Will Be Blood',
  'Nick of Time',
  'Collateral Damage',
  'Police Story',
  'The Front Runner',
  'The Cheetah Girls',
  'The Man Who Shot Liberty Valance',
  'Don Jon',
  'The Book of Life',
  'Bride and Prejudice',
  'The Reader',
  'Breakthrough',
  'Down to You',
  'Capernaum',
  'Maid in Manhattan',
  'The Running Man',
  'Marie Antoinette',
  'Widows',
  'Gremlins',
  'Cliffhanger',
  'The Texas Chainsaw Massacre',
  'The Aftermath',
  'A Nightmare on Elm Street The Dream Child',
  'Security',
  '500 Days of Summer',
  'The Outsiders',
  'Kill Chain',
  'A Conspiracy of Faith',
  'Little Nicky',
  'The Last Emperor',
  'Year One',
  'Jackie',
  'Carrie',
  'Enough',
  'Cuties',
  'Steve Jobs',
  'Overdrive',
  'Assassins',
  'The Great Beauty',
  'Presumed Innocent',
  'Truth or Dare',
  'Bloomington',
  'The Forgotten',
  'The Girl in the Spiders Web',
  'A Bigger Splash',
  'Rocky V',
  'Vacation',
  'New Jack City',
  'A Bridge Too Far',
  'The Swan Princess',
  'Teenage Mutant Ninja Turtles',
  'Silent Hill',
  'The Absent One',
  'Flight',
  'The Town',
  'The Purple Rose of Cairo',
  'April Fools Day',
  'Holmes and Watson',
  'The Dead Dont Die',
  'Three Colors Red',
  'Knocked Up',
  'The Neon Demon',
  'The Last Castle',
  'The Heat',
  'Awakenings',
  'What Happens in Vegas',
  'Along Came Polly',
  'Lupin the Third The Castle of Cagliostro',
  'Life As We Know It',
  'Lie with Me',
  'Papillon',
  'Bad Teacher',
  'After Earth',
  'Sweet Home Alabama',
  'Sahara',
  'Balkan Line',
  'True Legend',
  'The Sessions',
  'Underworld Blood Wars',
  'Live and Let Die',
  'Wild Tales',
  'Billy Lynns Long Halftime Walk',
  'Erin Brockovich',
  'The King of Comedy',
  'Boogie Nights',
  'Never Look Away',
  'GI Joe Retaliation',
  'Vox Lux',
  'Batman and Harley Quinn',
  'North by Northwest',
  'A Million Ways to Die in the West',
  'Overboard',
  'USS Indianapolis Men of Courage',
  'Steel Magnolias',
  'Top Secret',
  'Another Cinderella Story',
  'The Ring Two',
  'The Love Bug',
  'The Hummingbird Project',
  'The SpongeBob SquarePants Movie',
  'Johnny English Reborn',
  'Hard Target',
  'The English Teacher',
  'Spartacus',
  'Knock Knock',
  'Black Mirror Bandersnatch',
  'Dignitate',
  'Joy Ride',
  'Battle Star Wars',
  'Beverly Hills Cop',
  'The Bye Bye Man',
  'Baby Mama',
  'Away We Go',
  'Burlesque',
  'New Years Eve',
  'Just My Luck',
  'Death Warrant',
  'Good Luck Chuck',
  'El Mariachi',
  'The Secret in Their Eyes',
  'The Abyss',
  'The Count of Monte Cristo',
  'Drifters',
  'Ace Ventura When Nature Calls',
  'Stand by Me',
  'Frozen Fever',
  'Albert Nobbs',
  'Friday After Next',
  'The Assignment',
  'Wrong Turn 5 Bloodlines',
  'High Noon',
  'Arthur and the Invisibles',
  'Taken',
  'Our Brand Is Crisis',
  'Carriers',
  'The Duke',
  'Doom',
  'Georgia Rule',
  'Good People',
  'Hollow Man',
  'Triple 9',
  'The Wolfman',
  'Mrs Doubtfire',
  'Meet the Parents',
  '30 Days of Night',
  'Daughter of the Wolf',
  'Leprechaun',
  'Bulletproof',
  'Book of Shadows Blair Witch',
  'The Andromeda Strain',
  'November Criminals',
  'Poltergeist',
  'Home Alone The Holiday Heist',
  'The Grey',
  'Ballet Shoes',
  'Irrational Man',
  'Bridesmaids',
  'The Professional',
  'Sideways',
  'Pokemon The First Movie Mewtwo Strikes Back',
  'Anatomy of a Murder',
  'Colette',
  'Secret in Their Eyes',
  'The Adventures of Ichabod and Mr Toad',
  'Fitzcarraldo',
  'Due Date',
  'Kung Fu Panda Secrets of the Furious Five',
  'The Way Way Back',
  'Shut In',
  'Honey I Blew Up the Kid',
  'Confessions of a Shopaholic',
  'August Rush',
  'Road to Perdition',
  'Labor Pains',
  'The Return of Jafar',
  'Knight and Day',
  'Little Women',
  'About Love',
  'Winnie the Pooh',
  'Beyond the Reach',
  'One for the Money',
  'Cloud Atlas',
  'Max Payne',
  'The Farewell',
  'Judge Dredd',
  'Half Baked',
  'Carrie',
  'A Perfect Ending',
  'Only You',
  'Space Jam',
  'Apollo 11',
  '127 Hours',
  'Christine',
  'Bone Tomahawk',
  'The Many Adventures of Winnie the Pooh',
  'Valentine',
  'Imagine Me and You',
  'Wrath of the Titans',
  'Tinker Bell and the Great Fairy Rescue',
  'Patriots Day',
  'Match Point',
  'Scent of a Woman',
  'The Lives of Others',
  'The Waterboy',
  'A Perfect World',
  'Resident Evil Damnation',
  'The Guardian',
  'Blue Velvet',
  'The Rite',
  'The Snow Walker',
  'GI Jane',
  'Good Burger',
  'Gandhi',
  'Eraser',
  'Made of Honor',
  'The Producers',
  'Fools Gold',
  'Dazed and Confused',
  'Frankenweenie',
  'The Hunting Party',
  'The Poison Rose',
  'The Magnificent Seven',
  'Honey',
  'Push',
  'Only Yesterday',
  'GI Joe The Rise of Cobra',
  'City Hunter',
  'Tall Girl',
  'Bleach',
  'Think Like a Man Too',
  'Bad Santa',
  'The Student',
  'Payback',
  'Ray',
  'Always',
  'Girls Just Want to Have Fun',
  'Australia',
  'Lost Highway',
  'Heartbreak Ridge',
  'Escape from LA',
  'Spy Game',
  'From Beyond',
  'Once Upon a Time in China',
  'Cruel Intentions',
  'Saw',
  'Misery',
  'National Lampoons Christmas Vacation',
  'The Specialist',
  'Tower',
  'Anon',
  'Freddy Got Fingered',
  'The Cabinet of Dr Caligari',
  'You Dont Know Jack',
  'Over the Hedge',
  '21 Grams',
  'Dangerous Liaisons',
  'The Number 23',
  'Suck Me Shakespeer',
  'Red Cliff',
  'Once Upon a Time in China',
  'Secret Window',
  'Wild Strawberries',
  'The Horse Whisperer',
  'The Human Centipede',
  'American Reunion',
  'The Legend of Drunken Master',
  'Tango and Cash',
  'Stalker',
  'Bad Moms',
  '3000 Miles to Graceland',
  'Kicking and Screaming',
  'Hell or High Water',
  'Starman',
  'The Queens Corgi',
  'The Conjuring',
  'Hocus Pocus',
  'Wanted',
  'Mine',
  'Westworld',
  'Dead Silence',
  'Billy Madison',
  'Murder Most Foul',
  'The Muppets',
  'Stardust',
  'Femme Fatale',
  'Sister Act',
  'The Hangover',
  'A Cure for Wellness',
  'Bullet Head',
  'Birdy',
  'Crash',
  'Four Weddings and a Funeral',
  'Walking with Dinosaurs',
  'Asterix vs Caesar',
  'Lupin the Third vs Detective Conan',
  'A Monster Calls',
  'Jerry Maguire',
  'Patriot Games',
  'The Legend of 1900',
  'Blue Jasmine',
  'Tag',
  'I Origins',
  'A History of Violence',
  'Malcolm X',
  'Perfect Blue',
  'Day of the Dead Bloodline',
  'A Scanner Darkly',
  'DragonHeart',
  'The Duchess',
  'Overboard',
  'I Spit on Your Grave',
  'Lolita',
  'Milk Money',
  'Home Alone',
  'Gold',
  'Scary Movie',
  'Sweet November',
  'First Daughter',
  'Son of Batman',
  'Richie Rich',
  'Austin Powers The Spy Who Shagged Me',
  'Stuart Little',
  'The Ninth Gate',
  'Flashdance',
  'Basic',
  'Ronin',
  'The Karate Kid Part',
  'Hawaiian Vacation',
  'Unknown',
  'Role Models',
  'AI Rising',
  'Pain and Gain',
  'Pokemon',
  'Showgirls',
  'The Prodigy',
  'Noah',
  'War Horse',
  'War',
  'Barbie in the Nutcracker',
  'Leave No Trace',
  'New Nightmare',
  'The Beach',
  'The Talented Mr Ripley',
  'The Infiltrator',
  'The Scorpion King',
  'Alvin and the Chipmunks The Squeakquel',
  'The Informers',
  'The Crazies',
  'Clover',
  'Polaroid',
  'Zero Dark Thirty',
  'Dragon Ball Z Bojack Unbound',
  'The Holiday',
  'White Oleander',
  'Conspiracy Theory',
  'Horrible Bosses',
  'Before Sunset',
  'From Paris with Love',
  'Flight of the Phoenix',
  'Midnight Express',
  '47 Ronin',
  'The Physician',
  'Bulletproof Monk',
  'Finding Neverland',
  'The Three Musketeers',
  'Pooka Lives',
  'The Collector',
  'Deep Blue Sea',
  'Cape Fear',
  'Asterix Conquers America',
  'Ayirathil Oruvan',
  '3 from Hell',
  'The Alpha Test',
  'Man on the Moon',
  'Blair Witch',
  'Mia and the White Lion',
  'Point Break',
  'Cobra',
  'Christmas Inheritance',
  'Laws of Attraction',
  'Mechanic Resurrection',
  'Dinner for Schmucks',
  'Minions The Rise of Gru',
  'The Road Within',
  'The Golden Child',
  'Maverick',
  'Annie Hall',
  'Osmosis Jones',
  'Open Range',
  'Kung Fu Hustle',
  'Friday the 13th',
  'Magnolia',
  'Valentines Day',
];
